#!/bin/sh

POSIXLY_CORRECT=yes

DIR=$1

if [ ! -d $DIR ]; then
	echo "$DIR is not a directory!"
	exit 1
fi

echo "Root directory: $DIR"

dir_count=`find $DIR -type d 2> /dev/null | wc -l`

echo "Directories: $dir_count"

file_count=`find $DIR -type f 2> /dev/null | wc -l`

echo "All files: $file_count"


# FSHIST
echo "File size histogram:"

file_sizes=`find $DIR -type f -exec du -ba {} + | awk '{ print $1 }' | sort -n`

# < 100B
fshist="<100 B  :,"`echo "$file_sizes" | awk '$0<100' | wc -l`
# < 1 KiB
fshist="$fshist\n<1 KiB  :,"`echo "$file_sizes" | awk '$0<1024 && $0>=100' | wc -l`
# < 10 KiB
fshist="$fshist\n<10 KiB :,"`echo "$file_sizes" | awk '$0<10240 && $0>=1024' | wc -l`
# < 100 KiB
fshist="$fshist\n<100 KiB:,"`echo "$file_sizes" | awk '$0<102400 && $0>=10240' | wc -l`
# < 1 MiB
fshist="$fshist\n<1 MiB  :,"`echo "$file_sizes" | awk '$0<1048576 && $0>=102400' | wc -l`
# < 10 MiB
fshist="$fshist\n<10 MiB :,"`echo "$file_sizes" | awk '$0<10485760 && $0>=1048576' | wc -l`
# < 100 MiB
fshist="$fshist\n<100 MiB:,"`echo "$file_sizes" | awk '$0<104857600 && $0>=10485760' | wc -l`
# < 1 GiB
fshist="$fshist\n<1 GiB  :,"`echo "$file_sizes" | awk '$0<1073741824 && $0>=104857600' | wc -l`
# >= 1 GiB
fshist="$fshist\n>= GiB  :,"`echo "$file_sizes" | awk '$0>=1073741824' | wc -l`

SAVEIFS=$IFS
echo "$fshist" | while IFS= read -r line ; do
	echo "$line" | awk -F "," '{printf "  " $1 " "}'
	count=`echo "$line" | awk -F "," '{printf $2}'`
	echo "$line" | awk -v count=$count -F "," 'BEGIN {while (i++ < count) printf "#"}'
	echo ""
done
IFS=$SAVEIFS